disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "SeaTable"


[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "Jan 2, 2006"
  logo = "/images/seatable-logo.svg"
  footerPhrase = "Make powerful processes like thousands of others who use SeaTable daily."