disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "SeaTable"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "2 January 2006"
  logo = "/images/seatable-logo.svg"