# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier (relative path below content folder) of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Funktionen"
pageRef = "pages/functions"
weight = 10

[[main]]
name = "Produkte"
pageRef = "#0"
weight = 20

[[main]]
name = "Übersicht"
parent = "Produkte"
pageRef = "pages/product/overview"
weight = 21

[[main]]
name = "SeaTable Cloud"
parent = "Produkte"
pageRef = "pages/product/seatable-cloud"
weight = 22

[[main]]
name = "SeaTable Dedicated"
parent = "Produkte"
pageRef = "pages/product/seatable-dedicated"
weight = 23

[[main]]
name = "SeaTable Server"
parent = "Produkte"
pageRef = "pages/product/seatable-server"
weight = 24

[[main]]
name = "Lösungen"
pageRef = "#0"
weight = 30

[[main]]
name = "Marketing"
parent = "Lösungen"
pageRef = "pages/industry-solutions/marketing"
weight = 31

[[main]]
name = "Projektmanagement"
parent = "Lösungen"
pageRef = "pages/industry-solutions/project-management"
weight = 32

[[main]]
name = "HR"
parent = "Lösungen"
pageRef = "pages/industry-solutions/hr"
weight = 33

[[main]]
name = "Öffentlicher Dienst"
parent = "Lösungen"
pageRef = "pages/industry-solutions/public-service"
weight = 34

[[main]]
name = "Softwareentwicklung"
parent = "Lösungen"
pageRef = "pages/industry-solutions/software-development"
weight = 35

[[main]]
name = "Individuell"
parent = "Lösungen"
pageRef = "pages/industry-solutions/individual"
weight = 36

[[main]]
name = "Ressourcen"
pageRef = "#0"
weight = 40

[[main]]
name = "Vorlagen"
parent = "Ressourcen"
pageRef = "templates"
weight = 42

[[main]]
name = "Kurzanleitung"
parent = "Ressourcen"
pageRef = "pages/quick-guide"
weight = 43

[[main]]
name = "Online Kurse"
parent = "Ressourcen"
pageRef = "help/erste-schritte"
weight = 44

[[main]]
name = "Hilfe"
parent = "Ressourcen"
pageRef = "help"
weight = 45

#[[main]]
#name = "Integrationen"
#parent = "Ressourcen"
#pageRef = "posts"
#weight = 46

[[main]]
name = "Forum"
parent = "Ressourcen"
url = "https://forum.seatable.io"
weight = 47

[[main]]
name = "Blog"
parent = "Ressourcen"
pageRef = "posts"
weight = 48

[[main]]
name = "Preise"
pageRef = "pages/prices"
weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Produkte"
weight = 10

[[footer]]
name = "SeaTable Cloud"
parent = "Produkte"
pageRef = "pages/product/seatable-cloud"
weight = 11

[[footer]]
name = "SeaTable Dedicated"
parent = "Produkte"
pageRef = "pages/product/seatable-dedicated"
weight = 12

[[footer]]
name = "SeaTable Server"
parent = "Produkte"
pageRef = "pages/product/seatable-server"
weight = 13

[[footer]]
name = "Support"
parent = "Produkte"
pageRef = "pages/support"
weight = 14

[[footer]]
name = "Unterstützung"
weight = 20

[[footer]]
name = "Kurzanleitung"
parent = "Unterstützung"
pageref = "pages/quick-guide"
weight = 21

[[footer]]
name = "Hilfebereich"
parent = "Unterstützung"
pageRef = "help"
weight = 22

[[footer]]
name = "Vorlagen"
parent = "Unterstützung"
pageRef = "templates"
weight = 23

[[footer]]
name = "Integrationen"
parent = "Unterstützung"
pageRef = "pages/integrations"
weight = 24

[[footer]]
name = "Forum"
parent = "Unterstützung"
url = "https://forum.seatable.io"
weight = 25

[[footer]]
name = "Developer API"
parent = "Unterstützung"
url = "https://api.seatable.io"
weight = 26

[[footer]]
name = "Status"
parent = "Unterstützung"
url = "https://status.seatable.io"
weight = 27

[[footer]]
name = "Unternehmen"
weight = 30

[[footer]]
name = "Über uns"
parent = "Unternehmen"
pageRef = "pages/about"
weight = 31

[[footer]]
name = "Jobs"
parent = "Unternehmen"
pageRef = "pages/jobs"
weight = 32

[[footer]]
name = "Presse"
parent = "Unternehmen"
pageRef = "pages/press"
weight = 33

[[footer]]
name = "Kontakt"
parent = "Unternehmen"
pageRef = "pages/contact"
weight = 34

[[footer]]
name = "Blog"
parent = "Unternehmen"
pageRef = "posts"
weight = 35

# -- Legal Disclaimer --
# The last line of the page with links to the legal pages.

[[legal]]
name = "Impressum"
pageRef = "pages/legal/imprint"
weight = 10

[[legal]]
name = "Sicherheit"
pageRef = "pages/legal/security"
weight = 20

[[legal]]
name = "Datenschutz"
pageRef = "pages/legal/data-privacy"
weight = 30

[[legal]]
name = "Nutzungsbedingungen"
pageRef = "pages/legal/terms-of-service"
weight = 40

[[legal]]
name = "EULA"
pageRef = "pages/legal/eula"
weight = 50
