# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier (translationkey) of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Функции"
  pageRef = "pages/functions"
  weight = 10

[[main]]
  name = "Продукция"
  pageRef = "/"
  weight = 20

[[main]]
  name = "SeaTable Cloud"
  parent = "Продукция"
  pageRef = "pages/product/seatable-cloud"
  weight = 21

[[main]]
  name = "SeaTable Dedicated"
  parent = "Продукция"
  pageRef = "pages/product/seatable-dedicated"
  weight = 22

[[main]]
  name = "Сервер SeaTable"
  parent = "Продукция"
  pageRef = "pages/product/seatable-server"
  weight = 23

[[main]]
  name = "Отраслевые решения"
  pageRef = "#0"
  weight = 30

[[main]]
  name = "Маркетинг"
  parent = "Отраслевые решения"
  pageRef = "pages/industry-solutions/marketing"
  weight = 31

[[main]]
  name = "Управление проектами"
  parent = "Отраслевые решения"
  pageRef = "pages/industry-solutions/project-management"
  weight = 32

[[main]]
  name = "HR"
  parent = "Отраслевые решения"
  pageRef = "pages/industry-solutions/hr"
  weight = 33

[[main]]
  name = "Государственная служба"
  parent = "Отраслевые решения"
  pageRef = "pages/industry-solutions/public-service"
  weight = 34

[[main]]
  name = "Разработка программного обеспечения"
  parent = "Отраслевые решения"
  pageRef = "pages/industry-solutions/software-development"
  weight = 35

[[main]]
  name = "На заказ"
  parent = "Отраслевые решения"
  pageRef = "pages/industry-solutions/individual"
  weight = 36

[[main]]
  name = "Цены"
  pageRef = "pages/prices"
  weight = 40

[[main]]
  name = "Блог"
  pageRef = "posts"
  weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Продукция"
  weight = 10

[[footer]]
  name = "SeaTable Cloud"
  parent = "Продукция"
  pageRef = "pages/product/seatable-cloud"
  weight = 11

[[footer]]
  name = "SeaTable Dedicated"
  parent = "Продукция"
  pageRef = "pages/product/seatable-dedicated"
  weight = 12

[[footer]]
  name = "Сервер SeaTable"
  parent = "Продукция"
  pageRef = "pages/product/seatable-server"
  weight = 13

[[footer]]
  name = "Поддержка"
  parent = "Продукция"
  pageRef = "pages/support"
  weight = 14

[[footer]]
  name = "Поддержка"
  weight = 20

[[footer]]
  name = "Краткое руководство"
  parent = "Поддержка"
  url = "https://seatable.io/kurzanleitung/?lang=auto"
  weight = 21

[[footer]]
  name = "Зона помощи"
  parent = "Поддержка"
  url = "https://docs.seatable.io/?lang=auto"
  weight = 22

[[footer]]
  name = "Шаблоны"
  parent = "Поддержка"
  url = "https://seatable.io/vorlagen/?lang=auto"
  weight = 23

[[footer]]
  name = "Интеграции"
  parent = "Поддержка"
  url = "https://seatable.io/integrationen/?lang=auto"
  weight = 24

[[footer]]
  name = "Форум"
  parent = "Поддержка"
  url = "https://forum.seatable.io"
  weight = 25

[[footer]]
  name = "API для разработчиков"
  parent = "Поддержка"
  url = "https://api.seatable.io"
  weight = 26

[[footer]]
  name = "Статус"
  parent = "Поддержка"
  url = "https://status.seatable.io"
  weight = 27

[[footer]]
  name = "Компания"
  weight = 30

[[footer]]
  name = "О нас"
  parent = "Компания"
  pageRef = "pages/about"
  weight = 31

[[footer]]
  name = "Работа"
  parent = "Компания"
  pageRef = "pages/jobs"
  weight = 32

[[footer]]
  name = "Нажмите"
  parent = "Компания"
  pageRef = "pages/press"
  weight = 33

[[footer]]
  name = "Свяжитесь с нами"
  parent = "Компания"
  pageRef = "pages/contact"
  weight = 34

[[footer]]
  name = "Блог"
  parent = "Компания"
  pageRef = "posts"
  weight = 35

# -- Legal Disclaimer --
# The last line of the page with links to the legal pages.

[[legal]]
  name = "Оттиск"
  pageRef = "pages/legal/imprint"
  weight = 10

[[legal]]
  name = "Безопасность"
  pageRef = "pages/legal/security"
  weight = 20

[[legal]]
  name = "Защита данных"
  pageRef = "pages/legal/data-privacy"
  weight = 30

[[legal]]
  name = "Условия использования"
  pageRef = "pages/legal/terms-of-service"
  weight = 40

[[legal]]
  name = "EULA"
  pageRef = "pages/legal/eula"
  weight = 50
