# -- Main Menu --

[[main]]
  name = "Fonctions"
  pageRef = "functions"
  weight = 10

[[main]]
  name = "Produits"
  pageRef = "/"
  weight = 20

[[main]]
  name = "SeaTable Cloud"
  parent = "Produits"
  pageRef = "/"
  weight = 21

[[main]]
  name = "SeaTable Dédié"
  parent = "Produits"
  pageRef = "/"
  weight = 22

[[main]]
  name = "Serveur SeaTable"
  parent = "Produits"
  pageRef = "/"
  weight = 23

[[main]]
  name = "Solutions sectorielles"
  pageRef = "#0"
  weight = 30

[[main]]
  name = "Marketing"
  parent = "Solutions sectorielles"
  pageRef = "/"
  weight = 31

[[main]]
  name = "Gestion de projet"
  parent = "Solutions sectorielles"
  pageRef = "/"
  weight = 32

[[main]]
  name = "RH"
  parent = "Solutions sectorielles"
  pageRef = "https://www.google.de"
  weight = 33

[[main]]
  name = "Service public"
  parent = "Solutions sectorielles"
  pageRef = "https://www.google.de"
  weight = 34

[[main]]
  name = "Développement de logiciels"
  parent = "Solutions sectorielles"
  pageRef = "https://www.google.de"
  weight = 35

[[main]]
  name = "Individuel"
  parent = "Solutions sectorielles"
  pageRef = "https://www.google.de"
  weight = 36

[[main]]
  name = "Prix"
  pageRef = "prices"
  weight = 40

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page

[[footer]]
  name = "Mentions légales"
  pageRef = "imprint"
  weight = 10

[[footer]]
  name = "Sécurité"
  pageRef = "security"
  weight = 20

[[footer]]
  name = "Protection des données"
  pageRef = "data-privacy"
  weight = 30

[[footer]]
  name = "Conditions d'utilisation"
  pageRef = "terms-of-use"
  weight = 40

[[footer]]
  name = "CLUF"
  pageRef = "eula"
  weight = 50