[[main]]
  name = "Functions"
  pageRef = "functions"
  weight = 10

[[main]]
  name = 'Home'
  pageRef = '/'
  weight = 11

[[main]]
  name = 'Posts'
  pageRef = '/'
  weight = 20

[[main]]
  name = 'Tags'
  pageRef = '/'
  weight = 30
