# -- Main Menu --

[[main]]
  name = "Funktionen"
  pageRef = "functions"
  weight = 10

[[main]]
  name = "Produkte"
  pageRef = "/"
  weight = 20

[[main]]
  name = "SeaTable Cloud"
  parent = "Produkte"
  pageRef = "/"
  weight = 21

[[main]]
  name = "SeaTable Dedicated"
  parent = "Produkte"
  pageRef = "/"
  weight = 22

[[main]]
  name = "SeaTable Server"
  parent = "Produkte"
  pageRef = "/"
  weight = 23

[[main]]
  name = "Branchenlösungen"
  pageRef = "#0"
  weight = 30

[[main]]
  name = "Marketing"
  parent = "Branchenlösungen"
  pageRef = "/"
  weight = 31

[[main]]
  name = "Projektmanagement"
  parent = "Branchenlösungen"
  pageRef = "/"
  weight = 32

[[main]]
  name = "HR"
  parent = "Branchenlösungen"
  pageRef = "https://www.google.de"
  weight = 33

[[main]]
  name = "Öffentlicher Dienst"
  parent = "Branchenlösungen"
  pageRef = "https://www.google.de"
  weight = 34

[[main]]
  name = "Softwareentwicklung"
  parent = "Branchenlösungen"
  pageRef = "https://www.google.de"
  weight = 34

[[main]]
  name = "Individuell"
  parent = "Branchenlösungen"
  pageRef = "https://www.google.de"
  weight = 34

[[main]]
  name = "Preise"
  pageRef = "prices"
  weight = 40

[[main]]
  name = "Blog"
  pageRef = "/"
  weight = 50