# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier (relative path below content folder) of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Fonctions"
pageRef = "pages/functions"
weight = 10

[[main]]
name = "Produits"
pageRef = "#0"
weight = 20

[[main]]
name = "Vue d'ensemble"
parent = "Produits"
pageRef = "pages/product/overview"
weight = 21

[[main]]
name = "SeaTable Cloud"
parent = "Produits"
pageRef = "pages/product/seatable-cloud"
weight = 22

[[main]]
name = "SeaTable Dédié"
parent = "Produits"
pageRef = "pages/product/seatable-dedicated"
weight = 23

[[main]]
name = "Serveur SeaTable"
parent = "Produits"
pageRef = "pages/product/seatable-server"
weight = 24

[[main]]
name = "Solutions"
pageRef = "#0"
weight = 30

[[main]]
name = "Marketing"
parent = "Solutions"
pageRef = "pages/industry-solutions/marketing"
weight = 31

[[main]]
name = "Gestion de projet"
parent = "Solutions"
pageRef = "pages/industry-solutions/project-management"
weight = 32

[[main]]
name = "RH"
parent = "Solutions"
pageRef = "pages/industry-solutions/hr"
weight = 33

[[main]]
name = "Service public"
parent = "Solutions"
pageRef = "pages/industry-solutions/public-service"
weight = 34

[[main]]
name = "Développement de logiciels"
parent = "Solutions"
pageRef = "pages/industry-solutions/software-development"
weight = 35

[[main]]
name = "Individuel"
parent = "Solutions"
pageRef = "pages/industry-solutions/individual"
weight = 36

[[main]]
name = "Ressources"
pageRef = "#0"
weight = 40

[[main]]
name = "Modèles"
parent = "Ressources"
pageRef = "templates"
weight = 42

[[main]]
name = "Guide rapide"
parent = "Ressources"
pageRef = "pages/quick-guide"
weight = 43

[[main]]
name = "Cours en ligne"
parent = "Ressources"
pageRef = "help/erste-schritte"
weight = 44

[[main]]
name = "Aide"
parent = "Ressources"
pageRef = "help"
weight = 45

#[[main]]
#name = "Integrations"
#parent = "Ressources"
#pageRef = "posts"
#weight = 46

[[main]]
name = "Forum"
parent = "Ressources"
url = "https://forum.seatable.io"
weight = 47

[[main]]
name = "Blog"
parent = "Ressources"
pageRef = "posts"
weight = 48

[[main]]
name = "Prix"
pageRef = "pages/prices"
weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Produits"
weight = 10

[[footer]]
name = "SeaTable Cloud"
parent = "Produits"
pageRef = "pages/product/seatable-cloud"
weight = 11

[[footer]]
name = "SeaTable Dédié"
parent = "Produits"
pageRef = "pages/product/dedicated"
weight = 12

[[footer]]
name = "Serveur SeaTable"
parent = "Produits"
pageRef = "pages/product/seatable-server"
weight = 13

[[footer]]
name = "Support"
parent = "Produits"
pageRef = "pages/support"
weight = 14

[[footer]]
name = "Soutien"
weight = 20

[[footer]]
name = "Guide de démarrage rapide"
parent = "Soutien"
pageRef = "pages/quick-guide"
weight = 21

[[footer]]
name = "Zone d'aide"
parent = "Soutien"
pageRef = "help"
weight = 22

[[footer]]
name = "Modèles"
parent = "Soutien"
pageRef = "templates"
weight = 23

[[footer]]
name = "Intégrations"
parent = "Soutien"
pageRef = "pages/integrations"
weight = 24

[[footer]]
name = "Forum"
parent = "Soutien"
url = "https://forum.seatable.io"
weight = 25

[[footer]]
name = "API pour développeurs"
parent = "Soutien"
url = "https://api.seatable.io"
weight = 26

[[footer]]
name = "Statut"
parent = "Soutien"
url = "https://status.seatable.io"
weight = 27

[[footer]]
name = "Entreprise"
weight = 30

[[footer]]
name = "À propos de nous"
parent = "Entreprise"
pageRef = "about-us"
weight = 31

[[footer]]
name = "Emplois"
parent = "Entreprise"
pageRef = "jobs"
weight = 32

[[footer]]
name = "Presse"
parent = "Entreprise"
pageRef = "press"
weight = 33

[[footer]]
name = "Contact"
parent = "Entreprise"
pageRef = "contact-us"
weight = 34

[[footer]]
name = "Blog"
parent = "Entreprise"
pageRef = "posts"
weight = 35

# -- Legal Disclaimer --
# The last line of the page with links to the legal pages.

[[legal]]
name = "Mentions légales"
pageRef = "imprint"
weight = 10

[[legal]]
name = "Sécurité"
pageRef = "security"
weight = 20

[[legal]]
name = "Protection des données"
pageRef = "data-privacy"
weight = 30

[[legal]]
name = "Conditions d'utilisation"
pageRef = "terms-of-service"
weight = 40

[[legal]]
name = "CLUF"
pageRef = "eula"
weight = 50
