
[sitemap]
  excludedKinds = ["taxonomy", "term"]

[seo]
  matomoSiteId = "99"
  matomoProviderUrl = "https://wp-stats.seatable.io/"
  googleSearchConsoleVerificationTag = "iGenigAZSvwGpbLaeutS8SnDlLfYNsxtgZoDXMUNhFg"

[acticle]
  showHeadingAnchors = true