[sitemap]
excludedKinds = ["taxonomy", "term"]

[seo]
matomoSiteId = "6"
matomoProviderUrl = "https://wp-stats.seatable.io/"
googleSearchConsoleVerificationTag = "iGenigAZSvwGpbLaeutS8SnDlLfYNsxtgZoDXMUNhFg"

[acticle]
showHeadingAnchors = true
