services:
    ## Web Server / Reverse Proxy
    # Handles TLS termination using either Let's Encrypt or custom certificates
    caddy:
        image: ${IMAGE_CADDY:-lucaslorentz/caddy-docker-proxy:2.9.1-alpine}
        restart: unless-stopped
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=frontend-net
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/opt/caddy:/data/caddy'
            - ./public:/tmp/seatable.com
        networks:
            - frontend-net
        labels:
            caddy: https://${SEATABLE_HUGO_HOSTNAME:?Variable is not set or empty}
            caddy.root: /tmp/seatable.com
            caddy.import: /tmp/seatable.com/caddy_redirects.conf
            # Enable zstd/gzip compression
            caddy.encode:
            caddy.file_server:
            caddy.handle_errors: 404
            caddy.handle_errors.rewrite: '/404.html'
            caddy.handle_errors.file_server:
        healthcheck:
            test: ['CMD-SHELL', 'curl --fail http://localhost:2019/metrics || exit 1']
            start_period: 20s
            interval: 20s
            timeout: 5s
            retries: 3

networks:
    frontend-net:
        name: frontend-net
