name: Build

on:
    push:
        branches:
            - main
    #pull_request:
    #    branches:
    #        - main

env:
    GO_VERSION: 1.24.3
    MUFFET_VERSION: v2.11.0
    PAGEFIND_VERSION: 1.3.0

jobs:
    create-archive:
        name: Create archive
        runs-on: ubuntu-22.04
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetches entire commit history for git lastmod
            - name: Build site
              run: ./build.sh
            - name: Generate caddy_redirects.conf
              run: |
                  ./generate-caddy-redirects.sh
                  sudo cp caddy_redirects.conf src/public/
            - name: Validate Caddy config (local)
              run: |
                  echo -e "https://seatable.com {\nimport /tmp/caddy_redirects.conf\n}" > Caddyfile
                  docker run --rm -v ./Caddyfile:/tmp/Caddyfile -v ./src/public/caddy_redirects.conf:/tmp/caddy_redirects.conf lucaslorentz/caddy-docker-proxy:2.9.1-alpine validate --config /tmp/Caddyfile
            - name: Create tar.gz archive
              run: tar -czvf archive.tar.gz public
              working-directory: src
            - name: Upload tar.gz artifact
              uses: actions/upload-artifact@v4
              with:
                  name: site
                  path: src/archive.tar.gz

    check-links:
        name: Check links
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: actions/setup-go@v2
              with:
                  go-version: ${{ env.GO_VERSION }}
            - name: Start development server
              run: docker compose up -d
            - name: Add $GOPATH/bin to $PATH
              run: |
                  echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
            - name: Install muffet
              run: go install github.com/raviqqe/muffet/v2@${MUFFET_VERSION}
            - name: 'Wait until the container is healthy'
              uses: raschmitt/wait-for-healthy-container/@master
              with:
                  container-name: hugo
                  timeout: 240
            - name: Check links
              run: muffet -t60 -f -i 'http://127*' -i 'http://localhost' -e 'http://127.0.0.1:1313/pagefind/pagefind-ui.css' -e 'http://127.0.0.1:1313/pagefind/pagefind-ui.js' http://127.0.0.1:1313

    deploy:
        name: Deploy
        needs:
            - create-archive
            - check-links
        runs-on: ubuntu-22.04
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: site
            - name: Extract archive
              run: tar xf archive.tar.gz
            - name: Add SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: placeholder
            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            - name: Deploy with rsync
              # There's no target path after the last colon since rrsync is used on the server
              run: 'rsync -avz --delete . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:'
              working-directory: public
            - name: Validate Caddy config (remote)
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} validate-caddy-config
            - name: Reload Caddy config
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} reload-caddy-config
