name: Build

# TODO: Only on main?
on: push

jobs:
  create-archive:
    name: Create archive
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build site
        run: ./build.sh
      - name: Create tar.gz archive
        run: tar -czvf archive.tar.gz public
        working-directory: src
      # Step 4: Upload the archive as an artifact
      - name: Upload tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: src/archive.tar.gz
  deploy:
    name: Deploy
    needs: create-archive
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: Extract archive
        run: tar xf archive.tar.gz
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # TODO
          known_hosts: placeholder
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        # TODO: Add --delete
        # There's no target path after the last colon since rrsync is used on the server
        run: "rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:"
        working-directory: public
