name: Check Links

on: push

env:
  MUFFET_VERSION: v2.10.7

jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start development server
        run: docker compose up -d
      - name: Install muffet
        run: |
          curl -fsSL https://github.com/raviqqe/muffet/releases/download/${MUFFET_VERSION}/muffet_linux_amd64.tar.gz -O
          tar xf muffet_linux_amd64.tar.gz
      - name: Check links
        run: ./muffet -t60 -c10 -f -i 'http://127*' -i 'http://localhost' http://127.0.0.1:1313
